//error handling
try{
    console.log(a);

}catch(error){
    console.error("An error occurred:", error.message);
}